/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReverseEngineeringServicesRouteImport } from './routes/reverse-engineering-services'
import { Route as PrecisionManufacturingRouteImport } from './routes/precision-manufacturing'
import { Route as MouldDesignManufacturingRouteImport } from './routes/mould-design-manufacturing'
import { Route as IndustrialProductDevelopmentRouteImport } from './routes/industrial-product-development'
import { Route as CadModellingServicesRouteImport } from './routes/cad-modelling-services'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as R3dScanningServicesRouteImport } from './routes/3d-scanning-services'
import { Route as R3dScannerSalesRouteImport } from './routes/3d-scanner-sales'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as BlogCategoryCategoryRouteImport } from './routes/blog.category.$category'

const ReverseEngineeringServicesRoute =
  ReverseEngineeringServicesRouteImport.update({
    id: '/reverse-engineering-services',
    path: '/reverse-engineering-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrecisionManufacturingRoute = PrecisionManufacturingRouteImport.update({
  id: '/precision-manufacturing',
  path: '/precision-manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const MouldDesignManufacturingRoute =
  MouldDesignManufacturingRouteImport.update({
    id: '/mould-design-manufacturing',
    path: '/mould-design-manufacturing',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustrialProductDevelopmentRoute =
  IndustrialProductDevelopmentRouteImport.update({
    id: '/industrial-product-development',
    path: '/industrial-product-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const CadModellingServicesRoute = CadModellingServicesRouteImport.update({
  id: '/cad-modelling-services',
  path: '/cad-modelling-services',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dScanningServicesRoute = R3dScanningServicesRouteImport.update({
  id: '/3d-scanning-services',
  path: '/3d-scanning-services',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dScannerSalesRoute = R3dScannerSalesRouteImport.update({
  id: '/3d-scanner-sales',
  path: '/3d-scanner-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryCategoryRoute = BlogCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-scanner-sales': typeof R3dScannerSalesRoute
  '/3d-scanning-services': typeof R3dScanningServicesRoute
  '/blog': typeof BlogRouteWithChildren
  '/cad-modelling-services': typeof CadModellingServicesRoute
  '/industrial-product-development': typeof IndustrialProductDevelopmentRoute
  '/mould-design-manufacturing': typeof MouldDesignManufacturingRoute
  '/precision-manufacturing': typeof PrecisionManufacturingRoute
  '/reverse-engineering-services': typeof ReverseEngineeringServicesRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-scanner-sales': typeof R3dScannerSalesRoute
  '/3d-scanning-services': typeof R3dScanningServicesRoute
  '/cad-modelling-services': typeof CadModellingServicesRoute
  '/industrial-product-development': typeof IndustrialProductDevelopmentRoute
  '/mould-design-manufacturing': typeof MouldDesignManufacturingRoute
  '/precision-manufacturing': typeof PrecisionManufacturingRoute
  '/reverse-engineering-services': typeof ReverseEngineeringServicesRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d-scanner-sales': typeof R3dScannerSalesRoute
  '/3d-scanning-services': typeof R3dScanningServicesRoute
  '/blog': typeof BlogRouteWithChildren
  '/cad-modelling-services': typeof CadModellingServicesRoute
  '/industrial-product-development': typeof IndustrialProductDevelopmentRoute
  '/mould-design-manufacturing': typeof MouldDesignManufacturingRoute
  '/precision-manufacturing': typeof PrecisionManufacturingRoute
  '/reverse-engineering-services': typeof ReverseEngineeringServicesRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d-scanner-sales'
    | '/3d-scanning-services'
    | '/blog'
    | '/cad-modelling-services'
    | '/industrial-product-development'
    | '/mould-design-manufacturing'
    | '/precision-manufacturing'
    | '/reverse-engineering-services'
    | '/api/contact'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d-scanner-sales'
    | '/3d-scanning-services'
    | '/cad-modelling-services'
    | '/industrial-product-development'
    | '/mould-design-manufacturing'
    | '/precision-manufacturing'
    | '/reverse-engineering-services'
    | '/api/contact'
    | '/blog/$slug'
    | '/blog'
    | '/blog/category/$category'
  id:
    | '__root__'
    | '/'
    | '/3d-scanner-sales'
    | '/3d-scanning-services'
    | '/blog'
    | '/cad-modelling-services'
    | '/industrial-product-development'
    | '/mould-design-manufacturing'
    | '/precision-manufacturing'
    | '/reverse-engineering-services'
    | '/api/contact'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dScannerSalesRoute: typeof R3dScannerSalesRoute
  R3dScanningServicesRoute: typeof R3dScanningServicesRoute
  BlogRoute: typeof BlogRouteWithChildren
  CadModellingServicesRoute: typeof CadModellingServicesRoute
  IndustrialProductDevelopmentRoute: typeof IndustrialProductDevelopmentRoute
  MouldDesignManufacturingRoute: typeof MouldDesignManufacturingRoute
  PrecisionManufacturingRoute: typeof PrecisionManufacturingRoute
  ReverseEngineeringServicesRoute: typeof ReverseEngineeringServicesRoute
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reverse-engineering-services': {
      id: '/reverse-engineering-services'
      path: '/reverse-engineering-services'
      fullPath: '/reverse-engineering-services'
      preLoaderRoute: typeof ReverseEngineeringServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precision-manufacturing': {
      id: '/precision-manufacturing'
      path: '/precision-manufacturing'
      fullPath: '/precision-manufacturing'
      preLoaderRoute: typeof PrecisionManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mould-design-manufacturing': {
      id: '/mould-design-manufacturing'
      path: '/mould-design-manufacturing'
      fullPath: '/mould-design-manufacturing'
      preLoaderRoute: typeof MouldDesignManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrial-product-development': {
      id: '/industrial-product-development'
      path: '/industrial-product-development'
      fullPath: '/industrial-product-development'
      preLoaderRoute: typeof IndustrialProductDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cad-modelling-services': {
      id: '/cad-modelling-services'
      path: '/cad-modelling-services'
      fullPath: '/cad-modelling-services'
      preLoaderRoute: typeof CadModellingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-scanning-services': {
      id: '/3d-scanning-services'
      path: '/3d-scanning-services'
      fullPath: '/3d-scanning-services'
      preLoaderRoute: typeof R3dScanningServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-scanner-sales': {
      id: '/3d-scanner-sales'
      path: '/3d-scanner-sales'
      fullPath: '/3d-scanner-sales'
      preLoaderRoute: typeof R3dScannerSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$category': {
      id: '/blog/category/$category'
      path: '/category/$category'
      fullPath: '/blog/category/$category'
      preLoaderRoute: typeof BlogCategoryCategoryRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategoryCategoryRoute: typeof BlogCategoryCategoryRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategoryCategoryRoute: BlogCategoryCategoryRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dScannerSalesRoute: R3dScannerSalesRoute,
  R3dScanningServicesRoute: R3dScanningServicesRoute,
  BlogRoute: BlogRouteWithChildren,
  CadModellingServicesRoute: CadModellingServicesRoute,
  IndustrialProductDevelopmentRoute: IndustrialProductDevelopmentRoute,
  MouldDesignManufacturingRoute: MouldDesignManufacturingRoute,
  PrecisionManufacturingRoute: PrecisionManufacturingRoute,
  ReverseEngineeringServicesRoute: ReverseEngineeringServicesRoute,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
